development:
  adapter: postgresql
  encoding: unicode
  database: max_development
  pool: 5
  host: localhost
  username: postgres
  password: kl;'

test:
  adapter: postgresql
  encoding: unicode
  database: max_test
  pool: 5
  username: postgres
  password: kl;'
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: max_production
  pool: 5
  username: postgres
  password: kl;'
  url: <%= ENV['DATABASE_URL'] %>

staging:
  url: <%= ENV['DATABASE_URL'] %>